

const inicialState = {
    pokemons: [
        {
          "id": 1,
          "nombre": "bulbasaur",
          "vida": 45,
          "velocidad": 45,
          "ataque": 49,
          "defensa": 49,
          "tipo": "grass, poison",
          "peso": 69,
          "altura": 7,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
        },
        {
          "id": 2,
          "nombre": "ivysaur",
          "vida": 60,
          "velocidad": 60,
          "ataque": 62,
          "defensa": 63,
          "tipo": "grass, poison",
          "peso": 130,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"
        },
        {
          "id": 3,
          "nombre": "venusaur",
          "vida": 80,
          "velocidad": 80,
          "ataque": 82,
          "defensa": 83,
          "tipo": "grass, poison",
          "peso": 1000,
          "altura": 20,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"
        },
        {
          "id": 4,
          "nombre": "charmander",
          "vida": 39,
          "velocidad": 65,
          "ataque": 52,
          "defensa": 43,
          "tipo": "fire",
          "peso": 85,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"
        },
        {
          "id": 5,
          "nombre": "charmeleon",
          "vida": 58,
          "velocidad": 80,
          "ataque": 64,
          "defensa": 58,
          "tipo": "fire",
          "peso": 190,
          "altura": 11,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"
        },
        {
          "id": 6,
          "nombre": "charizard",
          "vida": 78,
          "velocidad": 100,
          "ataque": 84,
          "defensa": 78,
          "tipo": "fire, flying",
          "peso": 905,
          "altura": 17,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"
        },
        {
          "id": 7,
          "nombre": "squirtle",
          "vida": 44,
          "velocidad": 43,
          "ataque": 48,
          "defensa": 65,
          "tipo": "water",
          "peso": 90,
          "altura": 5,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png"
        },
        {
          "id": 8,
          "nombre": "wartortle",
          "vida": 59,
          "velocidad": 58,
          "ataque": 63,
          "defensa": 80,
          "tipo": "water",
          "peso": 225,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png"
        },
        {
          "id": 9,
          "nombre": "blastoise",
          "vida": 79,
          "velocidad": 78,
          "ataque": 83,
          "defensa": 100,
          "tipo": "water",
          "peso": 855,
          "altura": 16,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"
        },
        {
          "id": 10,
          "nombre": "caterpie",
          "vida": 45,
          "velocidad": 45,
          "ataque": 30,
          "defensa": 35,
          "tipo": "bug",
          "peso": 29,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png"
        },
        {
          "id": 11,
          "nombre": "metapod",
          "vida": 50,
          "velocidad": 30,
          "ataque": 20,
          "defensa": 55,
          "tipo": "bug",
          "peso": 99,
          "altura": 7,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png"
        },
        {
          "id": 12,
          "nombre": "butterfree",
          "vida": 60,
          "velocidad": 70,
          "ataque": 45,
          "defensa": 50,
          "tipo": "bug, flying",
          "peso": 320,
          "altura": 11,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png"
        },
        {
          "id": 13,
          "nombre": "weedle",
          "vida": 40,
          "velocidad": 50,
          "ataque": 35,
          "defensa": 30,
          "tipo": "bug, poison",
          "peso": 32,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png"
        },
        {
          "id": 14,
          "nombre": "kakuna",
          "vida": 45,
          "velocidad": 35,
          "ataque": 25,
          "defensa": 50,
          "tipo": "bug, poison",
          "peso": 100,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png"
        },
        {
          "id": 15,
          "nombre": "beedrill",
          "vida": 65,
          "velocidad": 75,
          "ataque": 90,
          "defensa": 40,
          "tipo": "bug, poison",
          "peso": 295,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png"
        },
        {
          "id": 16,
          "nombre": "pidgey",
          "vida": 40,
          "velocidad": 56,
          "ataque": 45,
          "defensa": 40,
          "tipo": "normal, flying",
          "peso": 18,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png"
        },
        {
          "id": 17,
          "nombre": "pidgeotto",
          "vida": 63,
          "velocidad": 71,
          "ataque": 60,
          "defensa": 55,
          "tipo": "normal, flying",
          "peso": 300,
          "altura": 11,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png"
        },
        {
          "id": 18,
          "nombre": "pidgeot",
          "vida": 83,
          "velocidad": 101,
          "ataque": 80,
          "defensa": 75,
          "tipo": "normal, flying",
          "peso": 395,
          "altura": 15,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png"
        },
        {
          "id": 19,
          "nombre": "rattata",
          "vida": 30,
          "velocidad": 72,
          "ataque": 56,
          "defensa": 35,
          "tipo": "normal",
          "peso": 35,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png"
        },
        {
          "id": 20,
          "nombre": "raticate",
          "vida": 55,
          "velocidad": 97,
          "ataque": 81,
          "defensa": 60,
          "tipo": "normal",
          "peso": 185,
          "altura": 7,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png"
        },
        {
          "id": 21,
          "nombre": "spearow",
          "vida": 40,
          "velocidad": 70,
          "ataque": 60,
          "defensa": 30,
          "tipo": "normal, flying",
          "peso": 20,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png"
        },
        {
          "id": 22,
          "nombre": "fearow",
          "vida": 65,
          "velocidad": 100,
          "ataque": 90,
          "defensa": 65,
          "tipo": "normal, flying",
          "peso": 380,
          "altura": 12,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png"
        },
        {
          "id": 23,
          "nombre": "ekans",
          "vida": 35,
          "velocidad": 55,
          "ataque": 60,
          "defensa": 44,
          "tipo": "poison",
          "peso": 69,
          "altura": 20,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png"
        },
        {
          "id": 24,
          "nombre": "arbok",
          "vida": 60,
          "velocidad": 80,
          "ataque": 95,
          "defensa": 69,
          "tipo": "poison",
          "peso": 650,
          "altura": 35,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png"
        },
        {
          "id": 25,
          "nombre": "pikachu",
          "vida": 35,
          "velocidad": 90,
          "ataque": 55,
          "defensa": 40,
          "tipo": "electric",
          "peso": 60,
          "altura": 4,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png"
        },
        {
          "id": 26,
          "nombre": "raichu",
          "vida": 60,
          "velocidad": 110,
          "ataque": 90,
          "defensa": 55,
          "tipo": "electric",
          "peso": 300,
          "altura": 8,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png"
        },
        {
          "id": 27,
          "nombre": "sandshrew",
          "vida": 50,
          "velocidad": 40,
          "ataque": 75,
          "defensa": 85,
          "tipo": "ground",
          "peso": 120,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png"
        },
        {
          "id": 28,
          "nombre": "sandslash",
          "vida": 75,
          "velocidad": 65,
          "ataque": 100,
          "defensa": 110,
          "tipo": "ground",
          "peso": 295,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png"
        },
        {
          "id": 29,
          "nombre": "nidoran-f",
          "vida": 55,
          "velocidad": 41,
          "ataque": 47,
          "defensa": 52,
          "tipo": "poison",
          "peso": 70,
          "altura": 4,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png"
        },
        {
          "id": 30,
          "nombre": "nidorina",
          "vida": 70,
          "velocidad": 56,
          "ataque": 62,
          "defensa": 67,
          "tipo": "poison",
          "peso": 200,
          "altura": 8,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png"
        },
        {
          "id": 31,
          "nombre": "nidoqueen",
          "vida": 90,
          "velocidad": 76,
          "ataque": 92,
          "defensa": 87,
          "tipo": "poison, ground",
          "peso": 600,
          "altura": 13,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png"
        },
        {
          "id": 32,
          "nombre": "nidoran-m",
          "vida": 46,
          "velocidad": 50,
          "ataque": 57,
          "defensa": 40,
          "tipo": "poison",
          "peso": 90,
          "altura": 5,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png"
        },
        {
          "id": 33,
          "nombre": "nidorino",
          "vida": 61,
          "velocidad": 65,
          "ataque": 72,
          "defensa": 57,
          "tipo": "poison",
          "peso": 195,
          "altura": 9,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png"
        },
        {
          "id": 34,
          "nombre": "nidoking",
          "vida": 81,
          "velocidad": 85,
          "ataque": 102,
          "defensa": 77,
          "tipo": "poison, ground",
          "peso": 620,
          "altura": 14,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png"
        },
        {
          "id": 35,
          "nombre": "clefairy",
          "vida": 70,
          "velocidad": 35,
          "ataque": 45,
          "defensa": 48,
          "tipo": "fairy",
          "peso": 75,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png"
        },
        {
          "id": 36,
          "nombre": "clefable",
          "vida": 95,
          "velocidad": 60,
          "ataque": 70,
          "defensa": 73,
          "tipo": "fairy",
          "peso": 400,
          "altura": 13,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png"
        },
        {
          "id": 37,
          "nombre": "vulpix",
          "vida": 38,
          "velocidad": 65,
          "ataque": 41,
          "defensa": 40,
          "tipo": "fire",
          "peso": 99,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png"
        },
        {
          "id": 38,
          "nombre": "ninetales",
          "vida": 73,
          "velocidad": 100,
          "ataque": 76,
          "defensa": 75,
          "tipo": "fire",
          "peso": 199,
          "altura": 11,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png"
        },
        {
          "id": 39,
          "nombre": "jigglypuff",
          "vida": 115,
          "velocidad": 20,
          "ataque": 45,
          "defensa": 20,
          "tipo": "normal, fairy",
          "peso": 55,
          "altura": 5,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png"
        },
        {
          "id": 40,
          "nombre": "wigglytuff",
          "vida": 140,
          "velocidad": 45,
          "ataque": 70,
          "defensa": 45,
          "tipo": "normal, fairy",
          "peso": 120,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png"
        },
        {
          "id": 41,
          "nombre": "zubat",
          "vida": 40,
          "velocidad": 55,
          "ataque": 45,
          "defensa": 35,
          "tipo": "poison, flying",
          "peso": 75,
          "altura": 8,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png"
        },
        {
          "id": 42,
          "nombre": "golbat",
          "vida": 75,
          "velocidad": 90,
          "ataque": 80,
          "defensa": 70,
          "tipo": "poison, flying",
          "peso": 550,
          "altura": 16,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png"
        },
        {
          "id": 43,
          "nombre": "oddish",
          "vida": 45,
          "velocidad": 30,
          "ataque": 50,
          "defensa": 55,
          "tipo": "grass, poison",
          "peso": 54,
          "altura": 5,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png"
        },
        {
          "id": 44,
          "nombre": "gloom",
          "vida": 60,
          "velocidad": 40,
          "ataque": 65,
          "defensa": 70,
          "tipo": "grass, poison",
          "peso": 86,
          "altura": 8,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png"
        },
        {
          "id": 45,
          "nombre": "vileplume",
          "vida": 75,
          "velocidad": 50,
          "ataque": 80,
          "defensa": 85,
          "tipo": "grass, poison",
          "peso": 186,
          "altura": 12,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png"
        },
        {
          "id": 46,
          "nombre": "paras",
          "vida": 35,
          "velocidad": 25,
          "ataque": 70,
          "defensa": 55,
          "tipo": "bug, grass",
          "peso": 54,
          "altura": 3,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png"
        },
        {
          "id": 47,
          "nombre": "parasect",
          "vida": 60,
          "velocidad": 30,
          "ataque": 95,
          "defensa": 80,
          "tipo": "bug, grass",
          "peso": 295,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png"
        },
        {
          "id": 48,
          "nombre": "venonat",
          "vida": 60,
          "velocidad": 45,
          "ataque": 55,
          "defensa": 50,
          "tipo": "bug, poison",
          "peso": 300,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png"
        },
        {
          "id": 49,
          "nombre": "venomoth",
          "vida": 70,
          "velocidad": 90,
          "ataque": 65,
          "defensa": 60,
          "tipo": "bug, poison",
          "peso": 125,
          "altura": 15,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png"
        },
        {
          "id": 50,
          "nombre": "diglett",
          "vida": 10,
          "velocidad": 95,
          "ataque": 55,
          "defensa": 25,
          "tipo": "ground",
          "peso": 8,
          "altura": 2,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png"
        },
        {
          "id": 51,
          "nombre": "dugtrio",
          "vida": 35,
          "velocidad": 120,
          "ataque": 100,
          "defensa": 50,
          "tipo": "ground",
          "peso": 333,
          "altura": 7,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png"
        },
        {
          "id": 52,
          "nombre": "meowth",
          "vida": 40,
          "velocidad": 90,
          "ataque": 45,
          "defensa": 35,
          "tipo": "normal",
          "peso": 42,
          "altura": 4,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png"
        },
        {
          "id": 53,
          "nombre": "persian",
          "vida": 65,
          "velocidad": 115,
          "ataque": 70,
          "defensa": 60,
          "tipo": "normal",
          "peso": 320,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png"
        },
        {
          "id": 54,
          "nombre": "psyduck",
          "vida": 50,
          "velocidad": 55,
          "ataque": 52,
          "defensa": 48,
          "tipo": "water",
          "peso": 196,
          "altura": 8,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png"
        },
        {
          "id": 55,
          "nombre": "golduck",
          "vida": 80,
          "velocidad": 85,
          "ataque": 82,
          "defensa": 78,
          "tipo": "water",
          "peso": 766,
          "altura": 17,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png"
        },
        {
          "id": 56,
          "nombre": "mankey",
          "vida": 40,
          "velocidad": 70,
          "ataque": 80,
          "defensa": 35,
          "tipo": "fighting",
          "peso": 280,
          "altura": 5,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png"
        },
        {
          "id": 57,
          "nombre": "primeape",
          "vida": 65,
          "velocidad": 95,
          "ataque": 105,
          "defensa": 60,
          "tipo": "fighting",
          "peso": 320,
          "altura": 10,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png"
        },
        {
          "id": 58,
          "nombre": "growlithe",
          "vida": 55,
          "velocidad": 60,
          "ataque": 70,
          "defensa": 45,
          "tipo": "fire",
          "peso": 190,
          "altura": 7,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png"
        },
        {
          "id": 59,
          "nombre": "arcanine",
          "vida": 90,
          "velocidad": 95,
          "ataque": 110,
          "defensa": 80,
          "tipo": "fire",
          "peso": 1550,
          "altura": 19,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png"
        },
        {
          "id": 60,
          "nombre": "poliwag",
          "vida": 40,
          "velocidad": 90,
          "ataque": 50,
          "defensa": 40,
          "tipo": "water",
          "peso": 124,
          "altura": 6,
          "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png"
        },
        {
          "id": "237e9bf7-646f-45ab-9539-04e8e3cc578a",
          "nombre": "Paola",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        },
        {
          "id": "a3b57b64-a01a-4087-a6b7-64687365c741",
          "nombre": "Paola",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        },
        {
          "id": "65ac3457-ba92-4759-92f1-814e8e6d795f",
          "nombre": "Paola",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        },
        {
          "id": "cf94992c-f4c1-4890-bd5a-938eebdea54f",
          "nombre": "Paola",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        },
        {
          "id": "25d182eb-3c20-4258-83aa-4de6158edec8",
          "nombre": "Paola",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        },
        {
          "id": "48da24c9-8ced-4e93-ad68-c28cd58d611a",
          "nombre": "Leo",
          "imagen": "jsdkfjas",
          "vida": 5,
          "ataque": "jdfkasj",
          "defensa": "jfaskf",
          "velocidad": null,
          "altura": null,
          "peso": null
        }
      ],
};

const rootReducer = (state = inicialState, action) => {
    switch (action.type) {
        default:
            return {...state}
}
}

export default rootReducer;
